FROM nvcr.io/nvidia/pyg:24.03-py3
# FROM nvcr.io/nvidia/pyg:23.11-py3

# FROM nvcr.io/nvidia/pytorch:24.03-py3

# RUN pip install --no-cache-dir torch_geometric
# # RUN pip install --no-cache-dir torch_geometric==2.0.3  # DataEdgeAttr pb

RUN pip install --no-cache-dir torch_cluster
RUN pip install --no-cache-dir torch_scatter
RUN pip install --no-cache-dir torch_sparse
RUN pip install --no-cache-dir e3nn==0.3.5
RUN pip install --no-cache-dir plotly wandb
